// Copyright © 2024 The ELPS authors

// Package perf provides call-graph-based performance analysis for ELPS
// source files. It detects hot paths, scaling risks, expensive-in-loop
// patterns, and recursive cycles by building and solving a call graph.
//
// The analysis has three passes:
//  1. Local scan — per-function AST walk producing FunctionSummary + CallEdge.
//  2. Graph construction — aggregates summaries into a CallGraph.
//  3. Solve — cycle detection, topological sort, score/scaling propagation,
//     and issue generation.
package perf

import "github.com/luthersystems/elps/parser/token"

// RuleID identifies a performance rule.
type RuleID string

const (
	// PERF001 flags functions whose total propagated cost exceeds the threshold.
	PERF001 RuleID = "PERF001"
	// PERF002 flags functions with scaling order at or above the threshold.
	PERF002 RuleID = "PERF002"
	// PERF003 flags expensive function calls nested inside loops.
	PERF003 RuleID = "PERF003"
	// PERF004 flags recursive call cycles.
	PERF004 RuleID = "PERF004"
	// UNKNOWN001 flags dynamic dispatch where callee cannot be resolved.
	UNKNOWN001 RuleID = "UNKNOWN001"
)

// Severity indicates the severity of a performance issue.
type Severity int

const (
	SeverityError Severity = iota + 1
	SeverityWarning
	SeverityInfo
)

func (s Severity) String() string {
	switch s {
	case SeverityError:
		return "error"
	case SeverityWarning:
		return "warning"
	case SeverityInfo:
		return "info"
	default:
		return "unknown"
	}
}

// CallContext describes where a call occurs relative to loops.
type CallContext struct {
	// LoopDepth is the nesting depth of loop forms at the call site.
	LoopDepth int
	// InLoop is true when LoopDepth > 0.
	InLoop bool
}

// CallEdge represents a call from one function to another.
type CallEdge struct {
	// Caller is the qualified name of the calling function.
	Caller string
	// Callee is the qualified name of the called function.
	Callee string
	// Source is the location of the call expression.
	Source *token.Location
	// Context describes the loop nesting at the call site.
	Context CallContext
	// IsExpensive is true if the callee matches an expensive function pattern.
	IsExpensive bool
}

// FunctionSummary holds analysis results for a single function.
type FunctionSummary struct {
	// Name is the qualified function name (package:name or just name).
	Name string
	// Source is the location of the function definition.
	Source *token.Location
	// File is the source file containing this function.
	File string
	// LocalCost is the base cost of the function body (before propagation).
	LocalCost int
	// MaxLoopDepth is the deepest loop nesting found in the function body.
	MaxLoopDepth int
	// Calls are the outgoing call edges from this function.
	Calls []CallEdge
	// SuppressAll is true if the function has a bare elps-analyze-disable comment.
	SuppressAll bool
	// SuppressedRules contains rule IDs suppressed for this function.
	SuppressedRules map[RuleID]bool
}

// CallGraph holds the complete call graph for a set of source files.
type CallGraph struct {
	// Functions maps qualified function names to their summaries.
	Functions map[string]*FunctionSummary
	// Edges is the complete set of call edges.
	Edges []CallEdge
}

// SolvedFunction holds propagated scores for a function after solving.
type SolvedFunction struct {
	// Name is the qualified function name.
	Name string
	// Source is the location of the function definition.
	Source *token.Location
	// File is the source file.
	File string
	// LocalCost is the base cost before propagation.
	LocalCost int
	// TotalScore is the propagated cost including callee contributions.
	TotalScore int
	// ScalingOrder is the propagated loop amplification factor.
	// 0 = O(1), 1 = O(N), 2 = O(N²), etc.
	ScalingOrder int
	// InCycle is true if this function participates in a recursive cycle.
	InCycle bool
}

// Issue is a performance diagnostic generated by the solver.
type Issue struct {
	// Rule identifies which performance rule triggered.
	Rule RuleID
	// Severity indicates the severity level.
	Severity Severity
	// Message is a human-readable description of the issue.
	Message string
	// Function is the function where the issue was detected.
	Function string
	// Source is the source location of the issue.
	Source *token.Location
	// File is the source file.
	File string
	// Details provides additional context (e.g., cycle members, call chain).
	Details []string
	// Fingerprint is a stable identifier for this issue across runs,
	// derived from sha256(file:function:rule)[:16].
	Fingerprint string
	// Trace is the call chain that explains why this issue was raised.
	// For PERF001/PERF002, it shows the hot path from caller to expensive leaf.
	// For PERF003, it shows the loop context.
	Trace []TraceEntry
}

// TraceEntry is a single step in a call chain trace.
type TraceEntry struct {
	// Function is the function name at this step.
	Function string
	// Source is the source location.
	Source *token.Location
	// Note describes what happens at this step (e.g., "calls db-put in loop (depth 1)").
	Note string
}
