version: "2"
run:
  timeout: 2m
linters:
  enable:
    - gosec
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1019" # Allow deprecated usage during migration to *Context methods
        - "-ST*"    # Preserve pre-existing style check behavior
