// Copyright © 2026 The ELPS authors

package lisp_test

import (
	"fmt"
	"sort"
	"strings"
	"testing"
	"time"
	"unsafe"

	"github.com/luthersystems/elps/internal/fuzzval"
	"github.com/luthersystems/elps/lisp"
	"github.com/luthersystems/elps/lisp/lisplib"
	"github.com/luthersystems/elps/parser"
)

// These tests prove the Detach contract (issues #362/#363): the detached
// value shares NO memory with the original.  "Prove" means two independent
// mechanisms, because each catches what the other cannot:
//
//  1. Pointer accounting: walk both graphs collecting every pointer identity
//     (*LVal nodes, Cells slice backing, bytes backing, MapData, CallStack
//     frames, Source locations, Meta tokens) and assert an empty
//     intersection.  This catches sharing even when nobody ever writes.
//
//  2. Aliasing writes: mutate the detached copy through every mutable
//     surface and assert the original's fingerprint is bit-for-bit
//     unchanged.  This catches backing storage the pointer walk does not
//     know to look for.
//
// The LArray backing is the case LVal.Copy deliberately fails, so a control
// test pins the difference: Copy DOES alias the array backing, Detach does
// not.

// detachTestEnv builds a full user env (needed for tagged values, lambda
// construction, and fuzzval).
func detachTestEnv(tb testing.TB) *lisp.LEnv {
	tb.Helper()
	env := lisp.NewEnv(nil)
	env.Runtime.Reader = parser.NewReader()
	if rc := lisp.InitializeUserEnv(env); rc.Type == lisp.LError {
		tb.Fatalf("initialize-user-env: %v", rc)
	}
	if rc := lisplib.LoadLibrary(env); rc.Type == lisp.LError {
		tb.Fatalf("load-library: %v", rc)
	}
	if rc := env.InPackage(lisp.String(lisp.DefaultUserPackage)); rc.Type == lisp.LError {
		tb.Fatalf("in-package: %v", rc)
	}
	return env
}

// ptrOf and sliceDataOf funnel every unsafe conversion in this file through
// two audited helpers: the resulting unsafe.Pointer values are ONLY compared
// for identity (map keys / == checks); nothing is ever dereferenced, written,
// or arithmetically adjusted through them.
func ptrOf[T any](p *T) unsafe.Pointer {
	return unsafe.Pointer(p) // #nosec G103 -- identity comparison only, never dereferenced.
}

func sliceDataOf[T any](s []T) unsafe.Pointer {
	return unsafe.Pointer(unsafe.SliceData(s)) // #nosec G103 -- identity comparison only, never dereferenced.
}

// walkGraph visits every LVal reachable from v exactly once, including
// sorted-map values (map keys are regenerated by Entries on every call and
// so are not part of the retained graph).
func walkGraph(v *lisp.LVal, seen map[*lisp.LVal]bool, visit func(*lisp.LVal)) {
	if v == nil || seen[v] {
		return
	}
	seen[v] = true
	visit(v)
	for _, c := range v.Cells {
		walkGraph(c, seen, visit)
	}
	if v.Type == lisp.LSortMap && v.Native != nil {
		md := v.Map()
		if md == nil || md.Map == nil {
			return
		}
		buf := make([]*lisp.LVal, md.Len())
		if lerr := md.Entries(buf); lerr.Type == lisp.LError {
			return
		}
		for _, pair := range buf {
			walkGraph(pair.Cells[1], seen, visit)
		}
	}
}

// collectMem returns every distinct pointer identity retained by v's graph,
// mapped to a description used in failure messages.
func collectMem(v *lisp.LVal) map[unsafe.Pointer]string {
	ptrs := make(map[unsafe.Pointer]string)
	add := func(p unsafe.Pointer, desc string) {
		if p != nil {
			ptrs[p] = desc
		}
	}
	walkGraph(v, make(map[*lisp.LVal]bool), func(n *lisp.LVal) {
		add(ptrOf(n), "*LVal("+n.Type.String()+")")
		if len(n.Cells) > 0 {
			add(sliceDataOf(n.Cells), "Cells backing of "+n.Type.String())
		}
		add(ptrOf(lisp.SourceLocForTest(n)), "Source location")
		if n.Meta != nil {
			add(ptrOf(n.Meta), "Meta")
			for _, t := range n.Meta.LeadingComments {
				add(ptrOf(t), "Meta leading comment token")
				add(ptrOf(t.Source), "Meta leading comment location")
			}
			for _, t := range n.Meta.InnerTrailingComments {
				add(ptrOf(t), "Meta inner trailing comment token")
				add(ptrOf(t.Source), "Meta inner trailing comment location")
			}
			if t := n.Meta.TrailingComment; t != nil {
				add(ptrOf(t), "Meta trailing comment token")
				add(ptrOf(t.Source), "Meta trailing comment location")
			}
		}
		switch native := n.Native.(type) {
		case *[]byte:
			add(ptrOf(native), "bytes slice header")
			if native != nil && len(*native) > 0 {
				add(sliceDataOf(*native), "bytes backing")
			}
		case *lisp.MapData:
			add(ptrOf(native), "MapData")
		case *lisp.CallStack:
			add(ptrOf(native), "CallStack")
			if native != nil {
				if len(native.Frames) > 0 {
					add(sliceDataOf(native.Frames), "CallStack frames backing")
				}
				if len(native.GoStack) > 0 {
					add(sliceDataOf(native.GoStack), "CallStack GoStack backing")
				}
				for i := range native.Frames {
					add(ptrOf(native.Frames[i].Source), "CallStack frame location")
				}
			}
		}
	})
	return ptrs
}

// assertDisjoint fails the test naming every pointer identity retained by
// both graphs.
func assertDetachDisjoint(t *testing.T, orig, detached *lisp.LVal) {
	t.Helper()
	a := collectMem(orig)
	b := collectMem(detached)
	for p, desc := range b {
		if origDesc, ok := a[p]; ok {
			t.Errorf("detached value shares memory with the original: %s (original: %s)", desc, origDesc)
		}
	}
}

// fingerprint renders v's full reachable graph deterministically, including
// internal aliasing structure (revisited nodes render as @id), scalar
// payloads, byte contents, sorted map entries, and source locations.  Two
// values with equal fingerprints are structurally identical; a fingerprint
// that survives deep mutation of another value proves the two share nothing
// mutable.
func fingerprint(v *lisp.LVal) string {
	f := &fingerprinter{ids: make(map[*lisp.LVal]int)}
	f.walk(v)
	return f.sb.String()
}

type fingerprinter struct {
	ids map[*lisp.LVal]int
	sb  strings.Builder
}

func (f *fingerprinter) walk(v *lisp.LVal) {
	if v == nil {
		f.sb.WriteString("<nil>;")
		return
	}
	if id, ok := f.ids[v]; ok {
		fmt.Fprintf(&f.sb, "@%d;", id)
		return
	}
	id := len(f.ids)
	f.ids[v] = id
	fmt.Fprintf(&f.sb, "#%d:%s q=%t str=%q int=%d float=%v", id, v.Type, v.Quoted, v.Str, v.Int, v.Float)
	if loc := lisp.SourceLocForTest(v); loc != nil {
		fmt.Fprintf(&f.sb, " src=%s:%d:%d", loc.File, loc.Line, loc.Col)
	}
	switch v.Type {
	case lisp.LBytes:
		if v.Native != nil {
			fmt.Fprintf(&f.sb, " bytes=%x", v.Bytes())
		}
	case lisp.LSortMap:
		f.walkMapEntries(v)
	case lisp.LError:
		if stack := v.CallStack(); stack != nil {
			fmt.Fprintf(&f.sb, " stack=%d", len(stack.Frames))
		}
	case lisp.LNative:
		fmt.Fprintf(&f.sb, " native=%T", v.Native)
	default:
	}
	f.sb.WriteString("[")
	for _, c := range v.Cells {
		f.walk(c)
	}
	f.sb.WriteString("];")
}

// walkMapEntries renders map entries sorted by key so the fingerprint does
// not depend on Go map iteration order.
func (f *fingerprinter) walkMapEntries(v *lisp.LVal) {
	if v.Native == nil {
		return
	}
	md := v.Map()
	if md == nil || md.Map == nil {
		return
	}
	buf := make([]*lisp.LVal, md.Len())
	if lerr := md.Entries(buf); lerr.Type == lisp.LError {
		f.sb.WriteString(" map=<error>")
		return
	}
	sort.Slice(buf, func(i, j int) bool {
		return buf[i].Cells[0].String() < buf[j].Cells[0].String()
	})
	for _, pair := range buf {
		fmt.Fprintf(&f.sb, " %s=>", pair.Cells[0])
		f.walk(pair.Cells[1])
	}
}

// mutateDeep writes through every mutable surface of v's graph: scalar
// fields, string fields, byte backing, and source locations.  Sorted-map
// values are reached through the generic walk.
func mutateDeep(v *lisp.LVal) {
	walkGraph(v, make(map[*lisp.LVal]bool), func(n *lisp.LVal) {
		n.Int++
		n.Float += 1.5
		switch n.Type {
		case lisp.LString, lisp.LSymbol, lisp.LQSymbol:
			n.Str += "-mutated"
		case lisp.LBytes:
			if n.Native != nil {
				b := n.Bytes()
				for i := range b {
					b[i] ^= 0xff
				}
			}
		default:
		}
		if loc := lisp.SourceLocForTest(n); loc != nil {
			loc.Line += 1000
			loc.File += "-mutated"
		}
	})
}

// buildRichValue constructs one value exercising every detachable shape:
// nested lists, scalars, bytes, a multi-entry sorted map with a compound
// value, an array, an error carrying a call stack, and a tagged value.
func buildRichValue(t *testing.T, env *lisp.LEnv) *lisp.LVal {
	t.Helper()
	inner := lisp.QExpr([]*lisp.LVal{
		lisp.Int(1), lisp.Float(2.5), lisp.String("s"), lisp.Symbol("sym"),
	})
	m := lisp.SortedMap()
	if lerr := m.MapSet("k", lisp.QExpr([]*lisp.LVal{lisp.Int(7), lisp.String("seven")})); lerr.Type == lisp.LError {
		t.Fatalf("map-set: %v", lerr)
	}
	if lerr := m.MapSet(lisp.Symbol("j"), lisp.Int(3)); lerr.Type == lisp.LError {
		t.Fatalf("map-set: %v", lerr)
	}
	arr := lisp.Array(nil, []*lisp.LVal{lisp.Int(10), lisp.Int(20), lisp.QExpr([]*lisp.LVal{lisp.Int(30)})})
	if arr.Type == lisp.LError {
		t.Fatalf("array: %v", arr)
	}
	// (error 'my-condition "boom") produces an LError whose Native holds the
	// call stack recorded at signal time.
	errv := env.LoadString("detach-test", `(error 'my-condition "boom")`)
	if errv.Type != lisp.LError {
		t.Fatalf("expected an LError value, got %v: %v", errv.Type, errv)
	}
	tagged := env.LoadString("detach-test-tagged", `(deftype dtch-point (p) p) (new dtch-point (list 1 2))`)
	if tagged.Type == lisp.LError {
		t.Fatalf("tagged value: %v", tagged)
	}
	return lisp.QExpr([]*lisp.LVal{
		inner, lisp.Bytes([]byte("hello world")), m, arr, errv, tagged,
	})
}

func TestDetachPointerDisjoint(t *testing.T) {
	env := detachTestEnv(t)
	orig := buildRichValue(t, env)
	before := fingerprint(orig)
	detached, err := orig.Detach()
	if err != nil {
		t.Fatalf("detach: %v", err)
	}
	assertDetachDisjoint(t, orig, detached)
	if fp := fingerprint(orig); fp != before {
		t.Errorf("detach mutated the original:\nbefore: %s\nafter:  %s", before, fp)
	}
	// The detached copy must also be structurally identical (source
	// locations included).
	if a, b := fingerprint(orig), fingerprint(detached); a != b {
		t.Errorf("detached copy is not structurally identical:\noriginal: %s\ndetached: %s", a, b)
	}
	// And mutating every mutable surface of the copy must leave the original
	// untouched — this catches any backing storage the pointer walk missed.
	mutateDeep(detached)
	if fp := fingerprint(orig); fp != before {
		t.Errorf("mutating the detached copy changed the original:\nbefore: %s\nafter:  %s", before, fp)
	}
}

// TestDetachParserOutput runs the same proof on real parser output — the
// exact shape substrate's parse cache stores (substrate#375) — in both
// normal and format-preserving modes (the latter populates Meta with comment
// tokens that must be detached too).
func TestDetachParserOutput(t *testing.T) {
	const src = `; leading comment
(defun fn (x) ; trailing comment
  (let ((m (sorted-map "a" 1 "b" (list 2 3))))
    (assoc! m "c" x)))
`
	for _, mode := range []struct {
		name   string
		reader lisp.Reader
	}{
		{"standard", parser.NewReader()},
		{"format-preserving", parser.NewReader(parser.WithFormatPreserving())},
	} {
		t.Run(mode.name, func(t *testing.T) {
			forms, err := mode.reader.Read("detach.lisp", strings.NewReader(src))
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			orig := lisp.QExpr(forms)
			before := fingerprint(orig)
			detached, derr := orig.Detach()
			if derr != nil {
				t.Fatalf("detach: %v", derr)
			}
			assertDetachDisjoint(t, orig, detached)
			mutateDeep(detached)
			if fp := fingerprint(orig); fp != before {
				t.Errorf("mutating the detached copy changed the original:\nbefore: %s\nafter:  %s", before, fp)
			}
		})
	}
}

// TestCopyAliasesArrayBacking is the CONTROL: it pins the exact behavior of
// Copy that makes it unusable as a transfer tool, so the Detach tests above
// are demonstrably testing a real difference and not a property Copy already
// had.
func TestCopyAliasesArrayBacking(t *testing.T) {
	arr := lisp.Array(nil, []*lisp.LVal{lisp.Int(10), lisp.Int(20), lisp.Int(30)})
	if arr.Type == lisp.LError {
		t.Fatalf("array: %v", arr)
	}
	cp := arr.Copy()
	if sliceDataOf(cp.Cells) != sliceDataOf(arr.Cells) {
		t.Fatalf("expected Copy to share the array's Cells backing (reference semantics); it did not")
	}
	// Writing an element through the copy is visible through the original:
	// Cells[1] is the shared row-major storage list.
	cp.Cells[1].Cells[0] = lisp.Int(999)
	if arr.Cells[1].Cells[0].Int != 999 {
		t.Fatalf("expected the write through Copy's backing to reach the original")
	}
}

func TestDetachArrayBackingDisjoint(t *testing.T) {
	arr := lisp.Array(nil, []*lisp.LVal{lisp.Int(10), lisp.Int(20), lisp.Int(30)})
	if arr.Type == lisp.LError {
		t.Fatalf("array: %v", arr)
	}
	detached, err := arr.Detach()
	if err != nil {
		t.Fatalf("detach: %v", err)
	}
	if sliceDataOf(detached.Cells) == sliceDataOf(arr.Cells) {
		t.Fatalf("detached array shares the Cells backing with the original")
	}
	if sliceDataOf(detached.Cells[1].Cells) == sliceDataOf(arr.Cells[1].Cells) {
		t.Fatalf("detached array shares the row-major storage backing with the original")
	}
	detached.Cells[1].Cells[0] = lisp.Int(999)
	detached.Cells[1].Cells[1].Int = 777
	if arr.Cells[1].Cells[0].Int != 10 || arr.Cells[1].Cells[1].Int != 20 {
		t.Fatalf("mutating the detached array changed the original: %v", arr)
	}
}

// TestCopyAliasesBytesAndMapValues pins the two other within-runtime sharing
// behaviors of Copy so the corresponding Detach assertions have controls.
func TestCopyAliasesBytesAndMapValues(t *testing.T) {
	b := lisp.Bytes([]byte("abc"))
	cp := b.Copy()
	cp.Bytes()[0] = 'X'
	if b.Bytes()[0] != 'X' {
		t.Fatalf("expected Copy to share LBytes backing; it did not")
	}

	m := lisp.SortedMap()
	val := lisp.QExpr([]*lisp.LVal{lisp.Int(1)})
	if lerr := m.MapSet("k", val); lerr.Type == lisp.LError {
		t.Fatalf("map-set: %v", lerr)
	}
	mcp := m.Copy()
	mval, _ := mcp.Map().Get(lisp.String("k"))
	mval.Cells[0] = lisp.Int(999)
	if val.Cells[0].Int != 999 {
		t.Fatalf("expected Copy to share sorted-map value pointers; it did not")
	}
}

func TestDetachBytesAndMapDisjoint(t *testing.T) {
	b := lisp.Bytes([]byte("abc"))
	db, err := b.Detach()
	if err != nil {
		t.Fatalf("detach bytes: %v", err)
	}
	db.Bytes()[0] = 'X'
	if b.Bytes()[0] != 'a' {
		t.Fatalf("mutating detached bytes changed the original: %q", b.Bytes())
	}

	m := lisp.SortedMap()
	val := lisp.QExpr([]*lisp.LVal{lisp.Int(1)})
	if lerr := m.MapSet("k", val); lerr.Type == lisp.LError {
		t.Fatalf("map-set: %v", lerr)
	}
	dm, err := m.Detach()
	if err != nil {
		t.Fatalf("detach map: %v", err)
	}
	dval, ok := dm.Map().Get(lisp.String("k"))
	if !ok {
		t.Fatalf("detached map lost key %q", "k")
	}
	dval.Cells[0] = lisp.Int(999)
	if val.Cells[0].Int != 1 {
		t.Fatalf("mutating a detached map value changed the original")
	}
	if lerr := dm.MapSet("k2", lisp.Int(2)); lerr.Type == lisp.LError {
		t.Fatalf("map-set on detached map: %v", lerr)
	}
	if _, found := m.Map().Get(lisp.String("k2")); found {
		t.Fatalf("assoc! on the detached map reached the original")
	}
}

// TestDetachPreservesInternalAliasing: internal sharing WITHIN a value is
// legitimate structure and must be mirrored in the copy — copied once,
// referenced twice — while still not aliasing the original.
func TestDetachPreservesInternalAliasing(t *testing.T) {
	shared := lisp.QExpr([]*lisp.LVal{lisp.Int(42)})
	orig := lisp.QExpr([]*lisp.LVal{shared, shared})
	detached, err := orig.Detach()
	if err != nil {
		t.Fatalf("detach: %v", err)
	}
	if detached.Cells[0] != detached.Cells[1] {
		t.Errorf("internal aliasing lost: copy.Cells[0] != copy.Cells[1]")
	}
	if detached.Cells[0] == orig.Cells[0] {
		t.Errorf("copy.Cells[0] aliases the original")
	}
}

// TestDetachCycle: lisp data can cycle; Detach must terminate and reproduce
// the same cycle within the copy.
func TestDetachCycle(t *testing.T) {
	orig := lisp.QExpr([]*lisp.LVal{lisp.Int(1), nil})
	orig.Cells[1] = orig
	detached, err := orig.Detach()
	if err != nil {
		t.Fatalf("detach: %v", err)
	}
	if detached.Cells[1] != detached {
		t.Errorf("cycle not preserved: copy.Cells[1] should be the copy itself")
	}
	if detached.Cells[1] == orig {
		t.Errorf("copy's cycle points into the original")
	}
}

// TestDetachRejectsNativeWithPath: an LNative payload cannot be hermetically
// copied, and passing it through silently would smuggle shared state while
// claiming isolation.  The error must name the path to the offending cell.
func TestDetachRejectsNativeWithPath(t *testing.T) {
	now := time.Now()
	orig := lisp.QExpr([]*lisp.LVal{
		lisp.Int(0),
		lisp.QExpr([]*lisp.LVal{
			lisp.Symbol("ok"),
			lisp.Native(&now),
		}),
	})
	_, err := orig.Detach()
	if err == nil {
		t.Fatalf("expected an error detaching a native value")
	}
	const want = "Cells[1].Cells[1]: native value (*time.Time) cannot be detached"
	if err.Error() != want {
		t.Errorf("wrong error:\n got: %s\nwant: %s", err, want)
	}

	// A native at the root has no path prefix.
	_, err = lisp.Native(&now).Detach()
	if err == nil || err.Error() != "native value (*time.Time) cannot be detached" {
		t.Errorf("wrong root error: %v", err)
	}
}

// TestDetachRejectsNativeInsideMap: the path must also thread through
// sorted-map values.
func TestDetachRejectsNativeInsideMap(t *testing.T) {
	now := time.Now()
	m := lisp.SortedMap()
	if lerr := m.MapSet("k", lisp.Native(&now)); lerr.Type == lisp.LError {
		t.Fatalf("map-set: %v", lerr)
	}
	orig := lisp.QExpr([]*lisp.LVal{lisp.Int(0), m})
	_, err := orig.Detach()
	if err == nil {
		t.Fatalf("expected an error detaching a native map value")
	}
	const want = `Cells[1].Map["k"]: native value (*time.Time) cannot be detached`
	if err.Error() != want {
		t.Errorf("wrong error:\n got: %s\nwant: %s", err, want)
	}
}

// TestDetachRejectsFunctions: builtins hold Go code, and lambdas capture
// their defining LEnv (and through it the whole source runtime), so both are
// rejected with the same path-bearing error style.
func TestDetachRejectsFunctions(t *testing.T) {
	env := detachTestEnv(t)

	builtin := env.GetGlobal(lisp.Symbol("lisp:car"))
	if builtin.Type != lisp.LFun {
		t.Fatalf("lookup car: got %v (%v)", builtin.Type, builtin)
	}
	_, err := lisp.QExpr([]*lisp.LVal{lisp.Int(0), builtin}).Detach()
	if err == nil {
		t.Fatalf("expected an error detaching a builtin")
	}
	if got := err.Error(); !strings.HasPrefix(got, "Cells[1]: builtin function cannot be detached") {
		t.Errorf("wrong builtin error: %s", got)
	}

	lambda := env.LoadString("detach-test", `(lambda (x) x)`)
	if lambda.Type != lisp.LFun {
		t.Fatalf("lambda: got %v (%v)", lambda.Type, lambda)
	}
	_, err = lisp.QExpr([]*lisp.LVal{lambda}).Detach()
	if err == nil {
		t.Fatalf("expected an error detaching a lambda")
	}
	if got := err.Error(); !strings.HasPrefix(got, "Cells[0]: function cannot be detached") {
		t.Errorf("wrong lambda error: %s", got)
	}
}

// TestDetachedASTEvaluates is the customer scenario end-to-end
// (substrate#375): parse once, Detach the cached AST, evaluate the detached
// copy in a completely different runtime.
func TestDetachedASTEvaluates(t *testing.T) {
	forms, err := parser.NewReader().Read("cached.lisp", strings.NewReader(`(+ 1 2)`))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	detached, derr := lisp.QExpr(forms).Detach()
	if derr != nil {
		t.Fatalf("detach: %v", derr)
	}
	env := detachTestEnv(t)
	result := env.Eval(detached.Cells[0])
	if result.Type != lisp.LInt || result.Int != 3 {
		t.Fatalf("detached AST evaluated to %v, want 3", result)
	}
}

// FuzzDetach: generate an arbitrary well-formed LVal, detach it, and prove
// isolation the same two ways as the unit tests — pointer accounting plus
// deep mutation of the copy with the original's fingerprint unchanged.
// Rejection (natives, functions) is a legitimate outcome; silent sharing is
// the bug being hunted.
func FuzzDetach(f *testing.F) {
	for _, seed := range fuzzval.Seeds() {
		f.Add(seed)
	}
	env := detachTestEnv(f)
	f.Fuzz(func(t *testing.T, data []byte) {
		g := fuzzval.New(data, env)
		orig := g.Value()
		detached, err := orig.Detach()
		if err != nil {
			if err.Error() == "" {
				t.Fatalf("rejection with empty error message")
			}
			return
		}
		before := fingerprint(orig)
		a := collectMem(orig)
		for p, desc := range collectMem(detached) {
			if origDesc, ok := a[p]; ok {
				t.Errorf("detached value shares memory with the original: %s (original: %s)", desc, origDesc)
			}
		}
		mutateDeep(detached)
		if after := fingerprint(orig); after != before {
			t.Fatalf("mutating the detached copy changed the original:\nbefore: %s\nafter:  %s", before, after)
		}
	})
}

// synthesizeSource builds a representative ELPS source of at least n bytes —
// the shape of a phylum: many function definitions over maps, lists, vectors
// and string/number literals.
func synthesizeSource(n int) string {
	var sb strings.Builder
	for i := 0; sb.Len() < n; i++ {
		fmt.Fprintf(&sb, `
(defun handler-%d (arg-one arg-two)
  (let ((m (assoc! (sorted-map "id" arg-one "n" %d) "k" (list 1 2.5 "str-%d" 'sym-%d)))
        (v (map 'list (lambda (x) (+ x %d)) '(1 2 3 4 5))))
    (if (equal? arg-one "case-%d")
        (vector 1 2 3 %d)
        (list m v "tail-%d" 0.125))))
`, i, i, i, i, i, i, i, i)
	}
	return sb.String()
}

// BenchmarkParse50KB is the baseline substrate pays today on every cache
// miss (and, absent Detach, what it would pay to avoid aliasing): parse the
// source from scratch.
func BenchmarkParse50KB(b *testing.B) {
	src := synthesizeSource(50 * 1024)
	b.SetBytes(int64(len(src)))
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		forms, err := parser.NewReader().Read("bench.lisp", strings.NewReader(src))
		if err != nil {
			b.Fatalf("parse: %v", err)
		}
		if len(forms) == 0 {
			b.Fatalf("no forms")
		}
	}
}

// BenchmarkDetach50KB is what a Detach-on-Get parse cache pays instead
// (substrate#375): one deep, hermetic copy of the cached AST.
func BenchmarkDetach50KB(b *testing.B) {
	src := synthesizeSource(50 * 1024)
	forms, err := parser.NewReader().Read("bench.lisp", strings.NewReader(src))
	if err != nil {
		b.Fatalf("parse: %v", err)
	}
	program := lisp.QExpr(forms)
	b.SetBytes(int64(len(src)))
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		detached, derr := program.Detach()
		if derr != nil {
			b.Fatalf("detach: %v", derr)
		}
		if len(detached.Cells) != len(forms) {
			b.Fatalf("bad detach")
		}
	}
}
