// Copyright © 2026 The ELPS authors

package lisp

import (
	"errors"
	"fmt"
	"reflect"
	"slices"
	"sort"

	"github.com/luthersystems/elps/internal/templatepolicy"
)

// Template is a privately owned construction plan for a loaded environment.
// Construct it with NewTemplate and instantiate independent VMs with NewVM.
// Mutable storage is copied once per backing object, including overlapping
// list and byte views. Transitively sealed program structure remains shared.
//
// The source must be quiescent during NewTemplate: no active evaluation and no
// concurrent mutation of its reachable state (see [NewTemplate]). Afterwards its
// mutable values may change without changing the plan. Environment, runtime and
// package state is represented by owned descriptors, not source objects.
// Concurrent NewVM calls are supported.
//
// Sharing immutable Go objects can retain their enclosing backing allocations,
// including inaccessible elements outside a slice's capacity. Thus Template
// does not guarantee garbage collection of the source VM when host-provided
// shared storage or services indirectly retain it (see the package documentation).
//
// As with Program, embedders must not write exported fields of sealed values
// or function formals/body vectors that contain shared sealed code.
// Reader, SourceLibrary, LoadCache and Stderr retain their shared-service contracts.
// Approved Go callbacks and native implementations remain trusted code: arbitrary
// hidden Go references cannot be discovered or isolated by the interpreter.
type Template struct {
	plan templatePlan
}

// TemplateOption configures admission of a loaded environment.
type TemplateOption func(*templateConfig)

type templateConfig struct {
	builtinPolicy func(*LVal) bool
	nativePolicy  func(any) bool
}

// TemplateWithBuiltinPolicy explicitly approves legacy Go builtin code for
// sharing. The predicate must attest that a callback captures no mutable VM data:
// it uses only immutable configuration, concurrency-safe host services, and the
// environment/arguments of its call. Shared services must not carry VM-local or
// request-bound state; callbacks obtain that state from each call's environment.
// ELPS's internal captured builtins expose VM state explicitly and need no such
// approval. Embedders attach mutable host state to each instance's context.
// A package name or a reflect function address is not evidence of this property.
// ELPS cannot inspect a Go closure or method receiver. Returning true for every
// builtin trusts every installed callback; it does not verify their captures.
// Embedders must audit their registrations and run ownership checks on host code.
// The policy runs during publication, not during each NewVM call.
func TemplateWithBuiltinPolicy(approve func(*LVal) bool) TemplateOption {
	return func(c *templateConfig) { c.builtinPolicy = approve }
}

// TemplateWithNativePolicy explicitly approves foreign immutable native payloads
// provided by the embedder. It is an assertion of transitive
// immutability, not a request to clone mutable data. A NativeCloner declaration
// does not make a payload admissible, and no clone callback is invoked. Mutable
// VM references belong in explicit builtin captures; host services are attached
// separately to each instance. Known diagnostic payloads (CallStack, *CallStack,
// and byte-header aliases into the live runtime stack) are always rejected,
// before this policy is consulted.
func TemplateWithNativePolicy(approve func(any) bool) TemplateOption {
	return func(c *templateConfig) { c.nativePolicy = approve }
}

// NewTemplate validates env and takes a private snapshot of its mutable state.
// It rejects partially sealed trees, unknown value types, and opaque Go state
// without an explicit immutability contract. In particular, a sealed
// ancestor cannot conceal a mutable descendant (issue #621).
// Retained CallStack or *CallStack payloads, including typed nil, are rejected
// under every value type and cannot be approved by a sharing policy. The live
// Runtime.Stack.GoStack must be nil, and no value may retain its byte-slice
// header, even while nil. Stack-free saved errors and errors generated by a VM
// after construction remain supported.
//
// The source must remain quiescent for this entire call: no evaluation in
// progress, no active call frames or condition handlers, and no concurrent
// mutation of its reachable state by another goroutine or host callback. The
// caller provides this exclusion. Rejecting recorded active evaluation state
// does not lock the source or synchronize with concurrent writers.
//
// Storage discovery uses numeric address arithmetic only at construction to
// identify overlapping backing ranges. It assumes Go's non-moving heap while
// retained source slices remain live. Numeric addresses are never converted
// back to pointers or dereferenced; memory is accessed through ordinary slices.
// The result stores ordinary Go slices and integer offsets, not source addresses.
//
// Initialization must itself be suitable for replay: transaction context, time,
// randomness and external effects must be bound per VM when cold loads do so.
func NewTemplate(env *LEnv, opts ...TemplateOption) (*Template, error) {
	if env == nil || env.Runtime == nil || env.Runtime.Registry == nil {
		return nil, errors.New("template: nil environment, runtime or registry")
	}
	if err := checkTemplateQuiescent(env.Runtime); err != nil {
		return nil, fmt.Errorf("template: %w", err)
	}
	var config templateConfig
	for _, opt := range opts {
		if opt == nil {
			return nil, errors.New("template: nil option")
		}
		opt(&config)
	}
	input := newTemplateInventory(config)
	if err := input.scan(env); err != nil {
		return nil, err
	}
	plan, err := compileTemplate(env, input)
	if err != nil {
		return nil, err
	}
	return &Template{plan: plan}, nil
}

// NewVM constructs an independent VM from the template. Mutable values use
// independent allocations, so retaining one returned scalar or byte view does
// not retain unrelated VM storage. Context and stderr may be set per instance.
func (t *Template) NewVM(opts ...VMOption) (*LEnv, error) {
	if t == nil || t.plan.root == 0 {
		return nil, errors.New("template: uninitialized template")
	}
	return t.plan.instantiate(opts)
}

// checkTemplateQuiescent rejects source state left inside an evaluation. The
// caller must also prevent concurrent evaluation throughout publication; this
// check does not synchronize with another goroutine evaluating the source.
func checkTemplateQuiescent(rt *Runtime) error {
	if rt.Stack == nil {
		return errors.New("runtime has no call stack")
	}
	// Recovered panics record their trace on an error's stack copy, never the
	// live runtime stack. Even empty nonnil storage violates that boundary.
	if rt.Stack.GoStack != nil {
		return errors.New("retained diagnostic stack: live runtime GoStack must be nil")
	}
	if n := len(rt.Stack.Frames); n != 0 {
		return fmt.Errorf("source not quiescent: call stack height %d", n)
	}
	if rt.evalDepth != 0 {
		return fmt.Errorf("source not quiescent: eval depth %d", rt.evalDepth)
	}
	if n := len(rt.conditionStack); n != 0 {
		return fmt.Errorf("source not quiescent: %d pending condition handlers", n)
	}
	return nil
}

type templateInventory struct {
	config      templateConfig
	values      map[*LVal]int // positive private index; zero is an admitted shared root
	envs        map[*LEnv]int
	sealed      map[*LVal]bool
	maps        map[*MapData]bool
	byteSeen    map[*[]byte]bool
	runtime     *Runtime
	valueQueue  []*LVal
	envQueue    []*LEnv
	cells       []templateCellSpan
	bytes       []templateByteSpan
	sharedCells []templateCellSpan
}

func newTemplateInventory(config templateConfig) *templateInventory {
	return &templateInventory{
		config: config,
		values: make(map[*LVal]int), envs: make(map[*LEnv]int),
		sealed: make(map[*LVal]bool), maps: make(map[*MapData]bool),
		byteSeen: make(map[*[]byte]bool),
	}
}

func (s *templateInventory) scan(env *LEnv) error {
	s.runtime = env.Runtime
	packages := sortedTemplateKeys(env.Runtime.Registry.packages)
	// Validate root identity before traversing any values or invoking policy.
	// Otherwise a differently named/unregistered current package could be
	// silently normalized or excluded from the published graph.
	for _, name := range packages {
		pkg := env.Runtime.Registry.packages[name]
		if pkg == nil {
			return fmt.Errorf("template: nil package %q", name)
		}
		if pkg.Name != name {
			return fmt.Errorf("template: registry key %q does not match package name %q", name, pkg.Name)
		}
	}
	if current := env.Runtime.Package; current != nil && env.Runtime.Registry.packages[current.Name] != current {
		return fmt.Errorf("template: current package %q is not registered by identity", current.Name)
	}
	if err := s.env(env); err != nil {
		return err
	}
	for _, name := range packages {
		pkg := env.Runtime.Registry.packages[name]
		for _, symbol := range sortedTemplateKeys(pkg.symbols) {
			if err := s.val(pkg.symbols[symbol]); err != nil {
				return fmt.Errorf("template: %s:%s: %w", name, symbol, err)
			}
		}
	}
	return s.checkSharedStorage()
}

func sortedTemplateKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func (s *templateInventory) env(env *LEnv) error {
	if env == nil {
		return nil
	}
	if _, seen := s.envs[env]; seen {
		return nil
	}
	if env.Runtime != s.runtime {
		return errors.New("captured environment belongs to another runtime")
	}
	s.envs[env] = len(s.envQueue) + 1
	s.envQueue = append(s.envQueue, env)
	for _, symbol := range sortedTemplateKeys(env.scope) {
		if err := s.val(env.scope[symbol]); err != nil {
			return fmt.Errorf("scope %s: %w", symbol, err)
		}
	}
	return s.env(env.parent)
}

// The known diagnostic category is independent of the LVal header and of host
// approval policies. Keep both mutable and sealed admission on this boundary.
func (s *templateInventory) checkDiagnosticPayload(payload any) error {
	switch payload := payload.(type) {
	case CallStack, *CallStack:
		return errors.New("retained diagnostic stack is not supported by templates")
	case *[]byte:
		if s.runtime != nil && s.runtime.Stack != nil && payload == &s.runtime.Stack.GoStack {
			// Identity matters even for a nil/zero-capacity slice: appending via
			// this header can otherwise change IsInternalPanic's marker (#629).
			return errors.New("retained diagnostic stack: byte header aliases live runtime GoStack")
		}
	}
	return nil
}

func (s *templateInventory) shared(v *LVal) error {
	if v == nil || s.sealed[v] {
		return nil
	}
	if err := s.checkDiagnosticPayload(v.Native); err != nil {
		return err
	}
	if !v.sealed || !sealableNodeType(v.Type) || v.Native != nil {
		return fmt.Errorf("sealed graph reaches mutable or opaque %s", v.Type)
	}
	// Debug metadata can reach unsealed macro arguments, including closures
	// over the source VM. The shared header cannot drop that edge as a mutable
	// descriptor does, so it must not be admitted as immutable syntax (#621).
	if v.macroExpansion != nil {
		return errors.New("sealed graph contains macro expansion metadata")
	}
	s.sealed[v] = true
	if cap(v.Cells) > 0 {
		s.sharedCells = append(s.sharedCells, newTemplateCellSpan(v))
	}
	// A Go caller can reslice up to capacity. SealAST visits visible children
	// only, so the seal bit is not evidence about a hidden capacity tail.
	for _, child := range v.Cells[:cap(v.Cells)] {
		if err := s.shared(child); err != nil {
			return err
		}
	}
	return nil
}

func (s *templateInventory) val(v *LVal) error {
	if v == nil {
		return nil
	}
	// Saved diagnostics can alias frames, locations and ordinary byte storage.
	// Reject the category, including typed nil and non-error headers, before
	// either a sharing policy or a header-specific path can admit it (#629).
	if err := s.checkDiagnosticPayload(v.Native); err != nil {
		return err
	}
	if _, seen := s.values[v]; seen {
		return nil
	}
	if v.sealed {
		s.values[v] = 0
		return s.shared(v)
	}
	if isSingleton(v) {
		s.values[v] = 0
	} else {
		s.values[v] = len(s.valueQueue) + 1
		s.valueQueue = append(s.valueQueue, v)
	}
	if v.Type <= LInvalid || v.Type >= LMarkTerminal {
		return fmt.Errorf("unsupported value type %s", v.Type)
	}
	switch v.Type {
	case LFun:
		fd, ok := v.Native.(*funData)
		if !ok || fd == nil {
			return errors.New("function has no function data")
		}
		if fd.captures != nil {
			if err := s.val(fd.captures.values); err != nil {
				return fmt.Errorf("builtin captures: %w", err)
			}
		} else if fd.builtin != nil && (s.config.builtinPolicy == nil || !s.config.builtinPolicy(v)) {
			return fmt.Errorf("builtin %s:%s has no template sharing declaration", fd.pkg, fd.fid)
		}
		if err := s.env(fd.env); err != nil {
			return err
		}
	case LNative:
		if err := s.native(v.Native); err != nil {
			return err
		}
	default:
		switch payload := v.Native.(type) {
		case nil:
		case *MapData:
			if err := s.mapData(payload); err != nil {
				return err
			}
		case *[]byte:
			if payload == nil {
				return errors.New("nil byte payload")
			}
			if !s.byteSeen[payload] {
				s.byteSeen[payload] = true
				if cap(*payload) > 0 {
					s.bytes = append(s.bytes, newTemplateByteSpan(payload))
				}
			}
		default:
			if err := s.native(payload); err != nil {
				return err
			}
		}
	}
	// Function bodies whose cells are all shared have immutable backing under
	// the existing function construction contract. Keep that fast path.
	sharedCells := v.Type == LFun && cap(v.Cells) == len(v.Cells)
	for _, child := range v.Cells {
		if child != nil && !child.sealed {
			sharedCells = false
		}
	}
	if cap(v.Cells) > 0 && !sharedCells {
		s.cells = append(s.cells, newTemplateCellSpan(v))
		// Capacity can expose additional cells through a later append or host
		// reslice. Validate and remap those references as part of the storage.
		for _, child := range v.Cells[:cap(v.Cells)] {
			if err := s.val(child); err != nil {
				return err
			}
		}
	} else {
		if cap(v.Cells) > 0 {
			s.sharedCells = append(s.sharedCells, newTemplateCellSpan(v))
		}
		for _, child := range v.Cells {
			if err := s.val(child); err != nil {
				return err
			}
		}
	}
	return nil
}

// A mutable wrapper over shared program storage is not made safe by copying
// only that wrapper: it changes the cold program's aliases. Reject this shape
// at admission, including wrappers over a function's shared body/formals.
func (s *templateInventory) checkSharedStorage() error {
	slices.SortFunc(s.cells, compareTemplateCellSpans)
	slices.SortFunc(s.sharedCells, compareTemplateCellSpans)
	i, j := 0, 0
	for i < len(s.cells) && j < len(s.sharedCells) {
		mutable, shared := s.cells[i], s.sharedCells[j]
		switch {
		case mutable.end <= shared.start:
			i++
		case shared.end <= mutable.start:
			j++
		default:
			return errors.New("template: mutable cells backing overlaps shared program storage")
		}
	}
	return nil
}

func (s *templateInventory) native(payload any) error {
	if payload == nil {
		return nil
	}
	// Pointer method sets inherit value markers, but a caller can replace a
	// whole pointee even when all its fields are private. Only audited struct
	// values receive automatic admission; pointer forms require host policy.
	if _, ok := payload.(templatepolicy.Immutable); ok && reflect.TypeOf(payload).Kind() == reflect.Struct {
		return nil
	}
	// Only actual scalar values have no hidden reference graph. A value struct
	// containing a map or slice is not made immutable by being held by value.
	switch reflect.TypeOf(payload).Kind() {
	case reflect.Bool, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64, reflect.Complex64, reflect.Complex128, reflect.String:
		return nil
	case reflect.Invalid, reflect.Uintptr, reflect.Array, reflect.Chan, reflect.Func,
		reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.Struct, reflect.UnsafePointer:
		// These kinds may hide mutable references or process-local identities.
	}
	if s.config.nativePolicy != nil && s.config.nativePolicy(payload) {
		return nil
	}
	return fmt.Errorf("native %T has no template immutability declaration", payload)
}

func (s *templateInventory) mapData(data *MapData) error {
	if data == nil || s.maps[data] {
		return nil
	}
	s.maps[data] = true
	switch backing := data.mapBacking.(type) {
	case nil:
		return nil
	case sortedmap:
		// Keys and type flags are Go scalars, not source value identities.
		// Avoid manufacturing temporary keys/pairs solely to discard them.
		for _, key := range sortedTemplateKeys(backing.m) {
			if err := s.val(backing.m[key]); err != nil {
				return err
			}
		}
	case jsonMap:
		if backing == nil {
			return errors.New("nil JSON map is not writable")
		}
		keys := sortedTemplateKeys(backing)
		// Reject malformed decoder storage before invoking admission callbacks.
		for _, key := range keys {
			if _, ok := backing[key].(*LVal); !ok {
				return fmt.Errorf("JSON map entry %q is not an LVal: %T", key, backing[key])
			}
		}
		for _, key := range keys {
			if err := s.val(backing[key].(*LVal)); err != nil {
				return err
			}
		}
	default:
		return fmt.Errorf("map backing %T is not interpreter-owned", data.mapBacking)
	}
	return nil
}
