// Copyright © 2026 The ELPS authors

package fuzzwatch

import (
	"errors"
	"go/build"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// NEGATIVE CONTROL for the #488 fix.
//
// The assertions in fuzzwatch_test.go and stall_probe_unix_test.go all pass on
// a Check that consults Starved at both caps. None of them proves that they
// would notice if the consultation were removed again -- a guard that can be
// deleted while every test stays green is a check that cannot fail, which is
// the defect class this fix belongs to.
//
// So: take the LIVE source file, delete the guard from a copy of it, compile
// that copy, and require the #488 verdict to come back. The copy is generated
// from the real file on every run rather than kept as a fixture, because a
// fixture drifts away from the thing it stands for and then the control tests
// history instead of the guard. If the guard can no longer be located the
// control fails loudly rather than silently testing nothing.
//
// Both directions are run through the same rig: the INTACT copy must fail the
// probe (the guard is doing something) and the STRIPPED copy must pass it (the
// vacuous verdict returns). Only running both distinguishes "the guard works"
// from "the rig is broken".

// starvationGuard is the block whose removal reproduces #488: the arm that
// asks whether the window was starved before calling it a hang.
const starvationGuard = "\t\tif r.Starved() {\n\t\t\treturn Inconclusive, 0, r\n\t\t}\n"

// controlProbe is compiled against each copy. It replays the window #488
// reported live -- a 30s budget, wall 1m24.561s, 54s of it lost -- and asserts
// the OLD verdict. It therefore fails against the fixed source and passes
// against the stripped source, which is exactly what makes it a control.
const controlProbe = `// Generated by TestTheStarvationGuardCanFail. Not checked in.
package fuzzwatch

import (
	"testing"
	"time"
)

func TestControlWindowIsReportedHung(t *testing.T) {
	b := New(30 * time.Second)
	b.startedAt = time.Now().Add(-84561 * time.Millisecond)
	b.lostAt = defaultMonitor.lost() - 54*time.Second
	v, _, r := b.Check()
	if !r.Starved() {
		t.Fatalf("rig broken: the control window is not starved (%s)", r)
	}
	if r.Scheduled() < 30*time.Second {
		t.Fatalf("rig broken: the control window does not spend the budget (%s)", r)
	}
	if v != Hung {
		t.Fatalf("verdict = %v, want Hung (%s)", v, r)
	}
}
`

func TestTheStarvationGuardCanFail(t *testing.T) {
	goBin := findGo(t)

	live, err := filepath.Abs("fuzzwatch.go")
	if err != nil {
		t.Fatalf("resolving the live source: %v", err)
	}
	raw, err := os.ReadFile(live) //nolint:gosec // the path is this package's own source file, resolved from the test's working directory
	if err != nil {
		t.Fatalf("reading %s: %v", live, err)
	}
	src := string(raw)

	if n := strings.Count(src, starvationGuard); n != 1 {
		t.Fatalf("expected exactly 1 starvation guard in %s, found %d -- the control cannot "+
			"locate what it is supposed to remove, so it is a check that cannot fail. "+
			"Has Check been restructured? Update starvationGuard to match.", live, n)
	}
	stripped := strings.Replace(src, starvationGuard, "", 1)
	if stripped == src {
		t.Fatal("stripping the guard changed nothing")
	}

	intactPassed := runControlProbe(t, goBin, "intact", src)
	strippedPassed := runControlProbe(t, goBin, "stripped", stripped)

	if intactPassed {
		t.Error("the control probe PASSED against the live source: Check still reports Hung for " +
			"the #488 window, so the fix is not in place")
	}
	if !strippedPassed {
		t.Error("the control probe FAILED against the stripped source: removing the starvation " +
			"guard did not restore the #488 verdict, so the assertions elsewhere in this package " +
			"may be passing for the wrong reason")
	}
	if !intactPassed && strippedPassed {
		t.Log("negative control: REMOVING the starvation guard restores the #488 verdict (Hung " +
			"for a starved window), so the guard is load-bearing")
	}
}

// runControlProbe compiles src as a standalone copy of this package alongside
// controlProbe and reports whether the probe passed.
func runControlProbe(t *testing.T, goBin, name, src string) bool {
	t.Helper()

	dir := t.TempDir()
	write := func(base, content string) {
		if err := os.WriteFile(filepath.Join(dir, base), []byte(content), 0o600); err != nil {
			t.Fatalf("%s: writing %s: %v", name, base, err)
		}
	}
	// An older `go` directive than any toolchain that could be running this,
	// so the copy never triggers a toolchain download in a sandbox with no
	// network. The package is stdlib-only, so there is nothing else to fetch.
	write("go.mod", "module fuzzwatchcontrol\n\ngo 1.23\n")
	write("fuzzwatch.go", src)
	write("control_probe_test.go", controlProbe)

	cmd := exec.CommandContext(t.Context(), goBin, "test", "-count=1", "-run", "^TestControlWindowIsReportedHung$", ".")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOFLAGS=", "GOTOOLCHAIN=local", "GOWORK=off")
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Logf("control (%s): probe PASSED\n%s", name, indent(string(out)))
		return true
	}
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) {
		t.Fatalf("%s: could not run the control probe at all: %v\n%s", name, err, out)
	}
	t.Logf("control (%s): probe FAILED\n%s", name, indent(string(out)))
	return false
}

func indent(s string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, l := range lines {
		lines[i] = "        | " + l
	}
	return strings.Join(lines, "\n")
}

// findGo locates a Go toolchain. This control must not skip when it cannot
// find one: a negative control that quietly opts out is indistinguishable from
// one that ran and found nothing wrong.
func findGo(t *testing.T) string {
	t.Helper()
	if p, err := exec.LookPath("go"); err == nil {
		return p
	}
	if root := build.Default.GOROOT; root != "" {
		p := filepath.Join(root, "bin", "go")
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	t.Fatal("no `go` binary on PATH or under GOROOT: the #488 negative control cannot compile " +
		"its stripped copy, so it cannot verify that the starvation guard is load-bearing")
	return ""
}
