// Copyright © 2026 The ELPS authors

package libhelp_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/luthersystems/elps/lisp"
	"github.com/luthersystems/elps/lisp/lisplib"
	"github.com/luthersystems/elps/parser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// helpGoldenEnv is a user-package environment with the full library and a few
// documented definitions, in user and in a second package.
func helpGoldenEnv(t *testing.T) (*lisp.LEnv, *bytes.Buffer) {
	t.Helper()
	env := lisp.NewEnv(nil)
	env.Runtime.Reader = parser.NewReader()
	var stderr bytes.Buffer
	env.Runtime.Stderr = &stderr
	require.NoError(t, lisp.GoError(lisp.InitializeUserEnv(env)))
	require.NoError(t, lisp.GoError(lisplib.LoadLibrary(env)))
	require.NoError(t, lisp.GoError(env.InPackage(lisp.String(lisp.DefaultUserPackage))))
	setup := `
(set 'documented-var 42 "The answer to everything.")
(set 'plain-var "hello")
(defun my-fn (a &optional b &rest c) "Adds things up.\n\nLonger description that goes on for a while so that the word wrapping at seventy two columns is exercised properly here." (+ a 1))
(defmacro my-mac (x) "A macro." (quasiquote (list (unquote x))))
(defun undoc (x) x)
(in-package 'other)
(set 'secret 7 "Other's secret.")
(lisp:in-package 'user)
`
	require.NoError(t, lisp.GoError(env.LoadString("setup", setup)))
	return env, &stderr
}

// TestHelpGolden pins lisp:help's output (issue #736).  The golden file was
// generated by help:help before help moved to core, and the output is byte
// for byte the same; the only difference is the function named in an error
// message, lisp:help where it was help:help.
func TestHelpGolden(t *testing.T) {
	env, stderr := helpGoldenEnv(t)
	var out bytes.Buffer
	for _, src := range []string{
		"(help documented-var)", "(help plain-var)", "(help map)", "(help lisp:map)", "(help my-fn)", "(help 'my-fn)",
		"(help my-mac)", "(help defun)", "(help let)", "(help undoc)", "(help other:secret)", "(help math:pi)",
		"(let ([local-x 3]) (help local-x))", "(help nosuch)", "(help string:join)", `(help "str")`,
	} {
		stderr.Reset()
		v := env.LoadString("test", src)
		// The golden file spells the call HELP so it reads the same for
		// help:help (which generated it) and lisp:help.
		out.WriteString(";; " + strings.Replace(src, "(help", "(HELP", 1) + "\n")
		out.Write(stderr.Bytes())
		if v.Type == lisp.LError {
			out.WriteString("ERROR: " + lisp.GoError(v).Error() + "\n")
		} else {
			out.WriteString("=> " + v.String() + "\n")
		}
	}
	want, err := os.ReadFile(filepath.Join("testdata", "help.golden"))
	require.NoError(t, err)
	assert.Equal(t, string(want), out.String())
}

// help is core: it resolves in the caller's package, from any package, and
// help:help is gone.  A library package's own help would look the name up in
// package help once library builtins run in their own package.
func TestHelpIsCore(t *testing.T) {
	env, stderr := helpGoldenEnv(t)
	for _, src := range []string{
		`(in-package 'mine)`,
		`(defun shadowed () "Mine's shadowed." 1)`,
		`(help shadowed)`,
	} {
		v := env.LoadString("test", src)
		require.NotEqual(t, lisp.LError, v.Type, "%s: %v", src, v)
	}
	assert.Equal(t, "function (shadowed)\n  Mine's shadowed.\n", stderr.String())

	helpVal := env.Get(lisp.Symbol("lisp:help"))
	require.Equal(t, lisp.LFun, helpVal.Type)
	assert.Equal(t, lisp.DefaultLangPackage, helpVal.Package())
	assert.True(t, helpVal.IsSpecialOp())

	v := env.LoadString("test", `(help:help shadowed)`)
	require.Equal(t, lisp.LError, v.Type)
	assert.Contains(t, lisp.GoError(v).Error(), "unbound symbol: help")
}

// The help package keeps its registry functions, now ordinary functions:
// the documented quoted spelling prints exactly what it did.
func TestHelpPackageFunctions(t *testing.T) {
	env, stderr := helpGoldenEnv(t)
	for _, name := range []string{"help-package", "help-package-symbols", "help-packages"} {
		v := env.Get(lisp.Symbol("help:" + name))
		require.Equal(t, lisp.LFun, v.Type, name)
		assert.False(t, v.IsSpecialFun(), "%s must be an ordinary function", name)
	}
	stderr.Reset()
	require.NoError(t, lisp.GoError(env.LoadString("test", `(help:help-package 'math)`)))
	assert.True(t, strings.HasPrefix(stderr.String(), "package math\n"), stderr.String())
	assert.Contains(t, stderr.String(), "float pi 3.141592653589793")

	v := env.LoadString("test", `(help:help-package "math")`)
	require.Equal(t, lisp.LError, v.Type)
	assert.Contains(t, lisp.GoError(v).Error(), "argument is not a symbol: 'string")
}
