// Copyright © 2026 The ELPS authors

package analysis

import (
	"github.com/luthersystems/elps/astutil"
	"github.com/luthersystems/elps/lisp"
	"github.com/luthersystems/elps/parser/token"
)

// MacroOrigin is the fact recorded on a definition that a macro call
// produced: which macro, in which package, and where the call is written. A
// definition generated by nested macros records the outermost call, the one
// that appears in the analyzed source.
//
// MacroOrigin holds plain data (no AST), so an embedder can keep it in an
// index and hand it back through Config.ExtraGlobals when analyzing another
// file, the way go/analysis passes facts between packages.
type MacroOrigin struct {
	// Macro is the head symbol of the macro call, as written.
	Macro string
	// Package is the package the call was expanded in.
	Package string
	// CallSite is the location of the macro call's head symbol, or nil when
	// the call carries no source location.
	CallSite *token.Location
}

// GeneratedDefinitions returns the package-level definitions (functions,
// macros, variables, types) that macro expansion produced, in source order,
// each with GeneratedBy set. It is empty unless Config.MacroExpander was set.
//
// A definition generated at top level is registered before the deep walk,
// like an ordinary defun, so references that precede the macro call resolve.
// Pass the result as Config.ExtraGlobals when analyzing other files so they
// can resolve, and report on, names that only exist after expansion.
func (r *Result) GeneratedDefinitions() []ExternalSymbol {
	if r == nil {
		return nil
	}
	var defs []ExternalSymbol
	for _, sym := range r.Symbols {
		if sym.GeneratedBy == nil || sym.External || sym.Scope == nil || sym.Scope.Kind != ScopeGlobal {
			continue
		}
		defs = append(defs, ExternalSymbol{
			Name:        sym.Name,
			Kind:        sym.Kind,
			Package:     sym.Package,
			Signature:   sym.Signature,
			Source:      sym.Source,
			DocString:   sym.DocString,
			GeneratedBy: sym.GeneratedBy,
		})
	}
	return defs
}

// isPackageFormHead reports heads that prescan handles itself and that are
// never offered to the MacroExpander there.
func isPackageFormHead(head string) bool {
	switch head {
	case "defun", "defmacro", "deftype", "set", "use-package", "in-package",
		"export", "lisp:export", "progn", "lisp:progn":
		return true
	}
	return false
}

// expand returns the MacroExpander's expansion of node in pkg, or nil when
// there is no expander, node's head is not a candidate macro (a builtin, a
// non-macro definition, a non-symbol) or expansion fails. Each call site and
// resolved head is expanded at most once per package per analysis, so prescan
// and the deep walk share expansions in the same package and import context.
func (a *analyzer) expand(node *lisp.LVal, scope *Scope, pkg string) *lisp.LVal {
	if a.cfg == nil || a.cfg.MacroExpander == nil || a.expansionDepth >= maxMacroExpansionDepth ||
		node == nil || node.Type != lisp.LSExpr || node.IsQuoted() ||
		len(node.Cells) == 0 || node.Cells[0].Type != lisp.LSymbol {
		return nil
	}
	if a.fileNonMacros[node.Cells[0].Str] {
		return nil
	}
	sym := scope.LookupInPackage(node.Cells[0].Str, pkg)
	if sym != nil && !isExpansionMacro(sym) {
		return nil
	}
	call := node
	if !a.fileMacros[expansionKey{pkg: pkg, head: node.Cells[0].Str}] {
		call = importedMacroCall(node, sym, pkg)
	}
	key := expansionKey{node: node, pkg: pkg, head: call.Cells[0].Str}
	if expanded, ok := a.expansions[key]; ok {
		return expanded
	}
	expanded := a.cfg.MacroExpander.ExpandMacro(call, pkg)
	if a.expansions == nil {
		a.expansions = make(map[expansionKey]*lisp.LVal)
	}
	a.expansions[key] = expanded
	return expanded
}

// expansionKey identifies a call in the package where it is expanded. The
// resolved head distinguishes imports introduced between shared occurrences.
type expansionKey struct {
	node *lisp.LVal
	pkg  string
	head string
}

// expansionPackageForms treats top-level progn bodies as top-level forms,
// including macro calls and in-package, before selecting nested declarations.
// Selecting declarations first would omit those calls and package switches,
// and visiting a progn plus its selected declarations would register them twice.
func expansionPackageForms(forms []*lisp.LVal) []*lisp.LVal {
	var out []*lisp.LVal
	for _, form := range forms {
		head := astutil.HeadSymbol(form)
		if form != nil && !form.IsQuoted() && (head == "progn" || head == "lisp:progn") {
			out = append(out, expansionPackageForms(form.Cells[1:])...)
		} else {
			out = append(out, astutil.PackageForms([]*lisp.LVal{form})...)
		}
	}
	return out
}

// withOrigin runs fn with call as the current macro origin (unless an outer
// call already is one) and records that origin on every package-level symbol
// fn defines.
func (a *analyzer) withOrigin(call *lisp.LVal, pkg string, fn func()) {
	first := len(a.result.Symbols)
	outer := a.origin == nil
	if outer {
		a.origin = &MacroOrigin{
			Macro:    call.Cells[0].Str,
			Package:  pkg,
			CallSite: astutil.SymbolLoc(call.Cells[0]),
		}
	}
	origin := a.origin
	fn()
	if outer {
		a.origin = nil
	}
	for _, sym := range a.result.Symbols[first:] {
		if sym.GeneratedBy == nil && sym.Scope == a.root {
			sym.GeneratedBy = origin
		}
	}
}

// packageExpansion holds expanded forms and their package state.
type packageExpansion struct {
	// forms contains expanded package forms.
	forms []*lisp.LVal
	// origins records each form's expansion origin.
	origins []*expansionKey
	// pkg is the active package name.
	pkg string
}

// expandPackageForms replaces each top-level macro call among forms with the
// package forms of its expansion, recursively, so prescan registers
// definitions a macro generates. The parallel origins slice records each
// occurrence's outermost call and its original package, even when expansions
// share form nodes. The returned package is the one in effect after all forms,
// including expanded ones.
func (a *analyzer) expandPackageForms(forms []*lisp.LVal, scope *Scope, pkg string, origin *expansionKey) packageExpansion {
	if a.cfg == nil || a.cfg.MacroExpander == nil {
		return packageExpansion{forms: forms, origins: nil, pkg: pkg}
	}
	if origin == nil && a.fileNonMacros == nil {
		// Prescan runs before the file's own definitions are registered, so
		// note which names the file defines as functions or variables: the
		// deep walk will resolve those heads to the file's definition and
		// never expand them, and prescan must agree. Likewise note the file's
		// own macros: the deep walk resolves those heads to the file's
		// definition, not to a macro an earlier use-package imported.
		a.fileNonMacros = map[string]bool{}
		a.fileMacros = map[expansionKey]bool{}
		filePkg := pkg
		for _, form := range forms {
			switch a.packageFormHead(form) {
			case "in-package":
				if astutil.ArgCount(form) >= 1 {
					if name := extractPackageName(form.Cells[1]); name != "" {
						filePkg = name
					}
				}
			case "defmacro":
				if astutil.ArgCount(form) >= 1 && form.Cells[1].Type == lisp.LSymbol {
					a.fileMacros[expansionKey{pkg: filePkg, head: form.Cells[1].Str}] = true
				}
			case "defun":
				if astutil.ArgCount(form) >= 1 && form.Cells[1].Type == lisp.LSymbol {
					a.fileNonMacros[form.Cells[1].Str] = true
				}
			case "set":
				if astutil.ArgCount(form) >= 1 {
					if name := extractSetSymbolName(form.Cells[1]); name != "" {
						a.fileNonMacros[name] = true
					}
				}
			}
		}
	}
	out := make([]*lisp.LVal, 0, len(forms))
	origins := make([]*expansionKey, 0, len(forms))
	for _, form := range forms {
		head := ""
		if form.Type == lisp.LSExpr && !form.IsQuoted() && len(form.Cells) > 0 {
			head = a.packageFormHead(form)
		}
		if head == "in-package" && astutil.ArgCount(form) >= 1 {
			if name := extractPackageName(form.Cells[1]); name != "" {
				pkg = name
			}
		}
		if head == "use-package" {
			// Later calls need these imports while expanding, before the
			// definition-registration pass replays the package forms.
			a.prescanUsePackage(form, scope, pkg)
		}
		var expanded *lisp.LVal
		if head != "" && !isPackageFormHead(head) {
			if _, custom := customDefLikeMatch(form, a.cfg); !custom {
				expanded = a.expand(form, scope, pkg)
			}
		}
		if expanded == nil {
			out = append(out, form)
			origins = append(origins, origin)
			continue
		}
		o := origin
		if o == nil {
			o = &expansionKey{node: form, pkg: pkg}
		}
		a.expansionDepth++
		var expandedForms []*lisp.LVal
		var expandedOrigins []*expansionKey
		expanded2 := a.expandPackageForms(expansionPackageForms([]*lisp.LVal{expanded}), scope, pkg, o)
		expandedForms, expandedOrigins, pkg = expanded2.forms, expanded2.origins, expanded2.pkg
		out = append(out, expandedForms...)
		origins = append(origins, expandedOrigins...)
		a.expansionDepth--
	}
	return packageExpansion{forms: out, origins: origins, pkg: pkg}
}
