// Copyright © 2026 The ELPS authors

package analysis

import (
	"github.com/luthersystems/elps/astutil"
	"github.com/luthersystems/elps/lisp"
	"github.com/luthersystems/elps/parser/token"
)

// MacroOrigin is the fact recorded on a definition that a macro call
// produced: which macro, in which package, and where the call is written. A
// definition generated by nested macros records the outermost call, the one
// that appears in the analyzed source.
//
// MacroOrigin holds plain data (no AST), so an embedder can keep it in an
// index and hand it back through Config.ExtraGlobals when analyzing another
// file, the way go/analysis passes facts between packages.
type MacroOrigin struct {
	// Macro is the head symbol of the macro call, as written.
	Macro string
	// Package is the package the call was expanded in.
	Package string
	// CallSite is the location of the macro call's head symbol, or nil when
	// the call carries no source location.
	CallSite *token.Location
}

// GeneratedDefinitions returns the package-level definitions (functions,
// macros, variables, types) that macro expansion produced, in source order,
// each with GeneratedBy set. It is empty unless Config.MacroExpander was set.
//
// A definition generated at top level is registered before the deep walk,
// like an ordinary defun, so references that precede the macro call resolve.
// Pass the result as Config.ExtraGlobals when analyzing other files so they
// can resolve, and report on, names that only exist after expansion.
func (r *Result) GeneratedDefinitions() []ExternalSymbol {
	if r == nil {
		return nil
	}
	var defs []ExternalSymbol
	for _, sym := range r.Symbols {
		if sym.GeneratedBy == nil || sym.External || sym.Scope == nil || sym.Scope.Kind != ScopeGlobal {
			continue
		}
		defs = append(defs, ExternalSymbol{
			Name:        sym.Name,
			Kind:        sym.Kind,
			Package:     sym.Package,
			Signature:   sym.Signature,
			Source:      sym.Source,
			DocString:   sym.DocString,
			GeneratedBy: sym.GeneratedBy,
		})
	}
	return defs
}

// isPackageFormHead reports heads that prescan handles itself and that are
// never offered to the MacroExpander there.
func isPackageFormHead(head string) bool {
	switch head {
	case "defun", "defmacro", "deftype", "set", "use-package", "in-package",
		"export", "lisp:export", "progn", "lisp:progn":
		return true
	}
	return false
}

// expand returns the MacroExpander's expansion of node in pkg, or nil when
// there is no expander, node's head is not a candidate macro (a builtin, a
// non-macro definition, a non-symbol) or expansion fails. Each call site is
// expanded at most once per analysis, so prescan and the deep walk see the
// same expanded nodes.
func (a *analyzer) expand(node *lisp.LVal, scope *Scope, pkg string) *lisp.LVal {
	if a.cfg == nil || a.cfg.MacroExpander == nil || a.expansionDepth >= maxMacroExpansionDepth ||
		node == nil || node.Type != lisp.LSExpr || node.IsQuoted() ||
		len(node.Cells) == 0 || node.Cells[0].Type != lisp.LSymbol {
		return nil
	}
	if a.fileNonMacros[node.Cells[0].Str] {
		return nil
	}
	sym := scope.Lookup(node.Cells[0].Str)
	if sym != nil && (sym.Kind != SymMacro || !isUserMacro(sym)) {
		return nil
	}
	if expanded, ok := a.expansions[node]; ok {
		return expanded
	}
	expanded := a.cfg.MacroExpander.ExpandMacro(node, pkg)
	if a.expansions == nil {
		a.expansions = make(map[*lisp.LVal]*lisp.LVal)
	}
	a.expansions[node] = expanded
	return expanded
}

// withOrigin runs fn with call as the current macro origin (unless an outer
// call already is one) and records that origin on every package-level symbol
// fn defines.
func (a *analyzer) withOrigin(call *lisp.LVal, pkg string, fn func()) {
	first := len(a.result.Symbols)
	outer := a.origin == nil
	if outer {
		a.origin = &MacroOrigin{
			Macro:    call.Cells[0].Str,
			Package:  pkg,
			CallSite: astutil.SymbolLoc(call.Cells[0]),
		}
	}
	origin := a.origin
	fn()
	if outer {
		a.origin = nil
	}
	for _, sym := range a.result.Symbols[first:] {
		if sym.GeneratedBy == nil && sym.Scope == a.root {
			sym.GeneratedBy = origin
		}
	}
}

// expandPackageForms replaces each top-level macro call among forms with the
// package forms of its expansion, recursively, so prescan registers
// definitions a macro generates. origins maps each form taken from an
// expansion to the outermost call that produced it.
func (a *analyzer) expandPackageForms(forms []*lisp.LVal, scope *Scope, pkg string, origin *lisp.LVal, origins map[*lisp.LVal]*lisp.LVal) []*lisp.LVal {
	if a.cfg == nil || a.cfg.MacroExpander == nil {
		return forms
	}
	if origin == nil && a.fileNonMacros == nil {
		// Prescan runs before the file's own definitions are registered, so
		// note which names the file defines as functions or variables: the
		// deep walk will resolve those heads to the file's definition and
		// never expand them, and prescan must agree.
		a.fileNonMacros = map[string]bool{}
		for _, form := range forms {
			switch astutil.HeadSymbol(form) {
			case "defun":
				if astutil.ArgCount(form) >= 1 && form.Cells[1].Type == lisp.LSymbol {
					a.fileNonMacros[form.Cells[1].Str] = true
				}
			case "set":
				if astutil.ArgCount(form) >= 1 {
					if name := extractSetSymbolName(form.Cells[1]); name != "" {
						a.fileNonMacros[name] = true
					}
				}
			}
		}
	}
	out := make([]*lisp.LVal, 0, len(forms))
	for _, form := range forms {
		head := ""
		if form.Type == lisp.LSExpr && !form.IsQuoted() && len(form.Cells) > 0 {
			head = astutil.HeadSymbol(form)
		}
		if head == "in-package" && astutil.ArgCount(form) >= 1 {
			if name := extractPackageName(form.Cells[1]); name != "" {
				pkg = name
			}
		}
		var expanded *lisp.LVal
		if head != "" && !isPackageFormHead(head) {
			if _, custom := customDefLikeMatch(form, a.cfg); !custom {
				expanded = a.expand(form, scope, pkg)
			}
		}
		if expanded == nil {
			if origin != nil {
				origins[form] = origin
			}
			out = append(out, form)
			continue
		}
		o := origin
		if o == nil {
			o = form
		}
		a.expansionDepth++
		out = append(out, a.expandPackageForms(astutil.PackageForms([]*lisp.LVal{expanded}), scope, pkg, o, origins)...)
		a.expansionDepth--
	}
	return out
}
